services:
  database:
    image: postgres
    container_name: health-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=health
    volumes:
      - pgdata:/var/lib/postgres

volumes:
  pgdata:
